/**
 * Catálogo de temas de color. Los valores de cada paleta viven en
 * `src/index.css` (`[data-theme="..."]`) — el CSS es la fuente de verdad
 * porque los componentes ya consumen `--bg`/`--fg`/`--accent`, y el exportador
 * de wallpapers lee las variables computadas en runtime. Acá solo vive la
 * metadata que la UI necesita: id, nombre visible y esquema claro/oscuro.
 */

export const themeIds = [
  "mono-dark",
  "mono-light",
  "gruvbox",
  "gruvbox-light",
  "nord",
  "ayu",
  "ayu-mirage",
  "ayu-light",
  "osaka",
  "tokyo-night",
  "catppuccin",
  "rose-pine",
  "rose-pine-dawn",
  "dracula",
  "solarized-dark",
  "solarized-light",
  "everforest",
  "kanagawa",
  "midnight",
  "vaporwave",
  "phosphor",
  "paper",
  "sakura",
  "matcha",
  "one-dark",
  "github-dark",
  "monokai",
  "night-owl",
  "material-ocean",
  "palenight",
  "synthwave",
  "cyberpunk",
  "horizon",
  "moonlight",
  "oceanic-next",
  "nightfox",
  "poimandres",
  "city-lights",
  "andromeda",
  "shades-of-purple",
  "cobalt",
  "sonokai",
  "zenburn",
  "amber",
  "blood-moon",
  "deep-sea",
  "aurora",
  "obsidian",
  "copper",
  "lavender-dusk",
  "forest-night",
  "ember",
  "ice",
  "coffee",
  "tomorrow-night",
  "neon-tokyo",
  "catppuccin-macchiato",
  "catppuccin-frappe",
  "one-light",
  "github-light",
  "catppuccin-latte",
  "tokyo-day",
  "night-owl-light",
  "material-light",
  "ocean-mist",
  "lemon",
  "coffee-cream",
  "lavender-mist",
  "peach",
  "arctic",
  "sepia",
  "mint",
  "blueprint-light",
] as const;

export type ThemeId = (typeof themeIds)[number];

export type ColorScheme = "dark" | "light";

export interface ThemeMeta {
  id: ThemeId;
  /** Nombre propio (no se traduce): el tema es una marca, como los presets. */
  name: string;
  scheme: ColorScheme;
}

export const themes: readonly ThemeMeta[] = [
  { id: "mono-dark", name: "Mono Dark", scheme: "dark" },
  { id: "mono-light", name: "Mono Light", scheme: "light" },
  { id: "gruvbox", name: "Gruvbox", scheme: "dark" },
  { id: "gruvbox-light", name: "Gruvbox Light", scheme: "light" },
  { id: "nord", name: "Nord", scheme: "dark" },
  { id: "ayu", name: "Ayu Dark", scheme: "dark" },
  { id: "ayu-mirage", name: "Ayu Mirage", scheme: "dark" },
  { id: "ayu-light", name: "Ayu Light", scheme: "light" },
  { id: "osaka", name: "Osaka", scheme: "dark" },
  { id: "tokyo-night", name: "Tokyo Night", scheme: "dark" },
  { id: "catppuccin", name: "Catppuccin", scheme: "dark" },
  { id: "rose-pine", name: "Rosé Pine", scheme: "dark" },
  { id: "rose-pine-dawn", name: "Rosé Pine Dawn", scheme: "light" },
  { id: "dracula", name: "Dracula", scheme: "dark" },
  { id: "solarized-dark", name: "Solarized Dark", scheme: "dark" },
  { id: "solarized-light", name: "Solarized Light", scheme: "light" },
  { id: "everforest", name: "Everforest", scheme: "dark" },
  { id: "kanagawa", name: "Kanagawa", scheme: "dark" },
  { id: "midnight", name: "Midnight Gold", scheme: "dark" },
  { id: "vaporwave", name: "Vaporwave", scheme: "dark" },
  { id: "phosphor", name: "Phosphor", scheme: "dark" },
  { id: "paper", name: "Paper & Ink", scheme: "light" },
  { id: "sakura", name: "Sakura", scheme: "light" },
  { id: "matcha", name: "Matcha", scheme: "light" },
  { id: "one-dark", name: "One Dark", scheme: "dark" },
  { id: "github-dark", name: "GitHub Dark", scheme: "dark" },
  { id: "monokai", name: "Monokai", scheme: "dark" },
  { id: "night-owl", name: "Night Owl", scheme: "dark" },
  { id: "material-ocean", name: "Material Ocean", scheme: "dark" },
  { id: "palenight", name: "Palenight", scheme: "dark" },
  { id: "synthwave", name: "Synthwave '84", scheme: "dark" },
  { id: "cyberpunk", name: "Cyberpunk", scheme: "dark" },
  { id: "horizon", name: "Horizon", scheme: "dark" },
  { id: "moonlight", name: "Moonlight", scheme: "dark" },
  { id: "oceanic-next", name: "Oceanic Next", scheme: "dark" },
  { id: "nightfox", name: "Nightfox", scheme: "dark" },
  { id: "poimandres", name: "Poimandres", scheme: "dark" },
  { id: "city-lights", name: "City Lights", scheme: "dark" },
  { id: "andromeda", name: "Andromeda", scheme: "dark" },
  { id: "shades-of-purple", name: "Shades of Purple", scheme: "dark" },
  { id: "cobalt", name: "Cobalt²", scheme: "dark" },
  { id: "sonokai", name: "Sonokai", scheme: "dark" },
  { id: "zenburn", name: "Zenburn", scheme: "dark" },
  { id: "amber", name: "Amber Terminal", scheme: "dark" },
  { id: "blood-moon", name: "Blood Moon", scheme: "dark" },
  { id: "deep-sea", name: "Deep Sea", scheme: "dark" },
  { id: "aurora", name: "Aurora", scheme: "dark" },
  { id: "obsidian", name: "Obsidian", scheme: "dark" },
  { id: "copper", name: "Copper", scheme: "dark" },
  { id: "lavender-dusk", name: "Lavender Dusk", scheme: "dark" },
  { id: "forest-night", name: "Forest Night", scheme: "dark" },
  { id: "ember", name: "Ember", scheme: "dark" },
  { id: "ice", name: "Ice", scheme: "dark" },
  { id: "coffee", name: "Coffee", scheme: "dark" },
  { id: "tomorrow-night", name: "Tomorrow Night", scheme: "dark" },
  { id: "neon-tokyo", name: "Neon Tokyo", scheme: "dark" },
  { id: "catppuccin-macchiato", name: "Catppuccin Macchiato", scheme: "dark" },
  { id: "catppuccin-frappe", name: "Catppuccin Frappé", scheme: "dark" },
  { id: "one-light", name: "One Light", scheme: "light" },
  { id: "github-light", name: "GitHub Light", scheme: "light" },
  { id: "catppuccin-latte", name: "Catppuccin Latte", scheme: "light" },
  { id: "tokyo-day", name: "Tokyo Day", scheme: "light" },
  { id: "night-owl-light", name: "Night Owl Light", scheme: "light" },
  { id: "material-light", name: "Material Light", scheme: "light" },
  { id: "ocean-mist", name: "Ocean Mist", scheme: "light" },
  { id: "lemon", name: "Lemon", scheme: "light" },
  { id: "coffee-cream", name: "Coffee Cream", scheme: "light" },
  { id: "lavender-mist", name: "Lavender Mist", scheme: "light" },
  { id: "peach", name: "Peach", scheme: "light" },
  { id: "arctic", name: "Arctic", scheme: "light" },
  { id: "sepia", name: "Sepia", scheme: "light" },
  { id: "mint", name: "Mint", scheme: "light" },
  { id: "blueprint-light", name: "Blueprint Light", scheme: "light" },
];

const byId = new Map<ThemeId, ThemeMeta>(themes.map((theme) => [theme.id, theme]));

export function themeMeta(id: ThemeId): ThemeMeta {
  // El mapa se construye desde `themes`, así que todo ThemeId tiene entrada.
  return byId.get(id) ?? { id: "mono-dark", name: "Mono Dark", scheme: "dark" };
}

export function isThemeId(value: unknown): value is ThemeId {
  return (themeIds as readonly unknown[]).includes(value);
}
